[package]
name = "fanuc_rmi"
version = "0.1.0"
edition = "2021"

[dependencies]
tokio = { version = "1", features = ["full"] }
serde = { version = "1.0", features = ["derive"] }
# bevy = { default-features = false, features = ["bevy_ecs"] }
serde_derive = "1.0"
serde_json = "1.0"