[package]
name = "shared_def"
version = "0.1.0"
edition = "2021"

[dependencies]
tokio = { version = "1", features = ["full"] }
# serde = { version = "1", features = ["derive"] }
# serde_json = "1.0"
serde = "1.0"
serde_derive = "1.0"
serde_json = "1.0"